### ISSUE TITLE
Display the featured images

### ISSUE THREAD

**Issue by eliasfaical** [bpk68/wordpress-next-starter#12]
Hello, I'm following your tutorial and creating a website with this stack. I have a question, how would I display the featured images on the single page [slug].js?

<img src={postData.featuredImage.node.mediaItemUrl} alt="" />

**Comment by bpk68** [comment]
Hey @eliasfaical did you get this sorted in the end? Let me know if you still need help 😊

**Comment by eliasfaical** [comment]
Hi, thanks, I managed to solve it! The names of the ACF fields were different.

extraPostInfo {
  authorExcerpt
  thumbnailImage {
    mediaItemUrl
  }
}

**Comment by eliasfaical** [comment]
Hey @bpk68 if i need to consume the custom post type data, for example "Cases", do I create a new file for my queries? 

Example:
> lib/apiCases.js

**Comment by bpk68** [comment]
Completely up to you. I tend to keep everything in the `/lib/api.js` file, but it's understandable that you might want to keep queries in multiple files depending on how your project grows. Next doesn't care though as your component or page or whatever will import the file where the queries live.

**Comment by eliasfaical** [comment]
Thanks for answering.
I am managing to go further and I came across a doubt. Do you have an example of how you would get the Menu items?

**Comment by bpk68** [comment]
I'm afraid I don't. I did use them pulled from WP at one point, but I believe you'll find this article helpful >>> https://www.wpgraphql.com/docs/menus/

I'll close this off now as it's not really an issue with the code base. Best of luck with your WP + GraphQL + Next adventure sir 😊
