### ISSUE TITLE
Can't fetch API

### ISSUE THREAD

**Issue by clebershimizu** [bpk68/wordpress-next-starter#13]
Hello,
I tried both following your tutorial and cloning your repo. When I run in development, I can`t fetch the API.

FetchError: invalid json response body at https://www.mydomainforwordpress.com/graphql reason: Unexpected token < in JSON at position 0

Could you please help me?

**Comment by bpk68** [comment]
Hey 😊

It looks like that domain isn't loading anything. Have you got a WordPress instance set up on there with the correct GraphQL plugins (i.e. WPGraphQL)?

**Comment by clebershimizu** [comment]
Hey Rob!
I really appreciate your answer and time, thank you.
The real domain is clebershimizu.com/graphql and it works with this
example:
https://github.com/vercel/next.js/tree/canary/examples/cms-wordpress
But I counldn't make it work with yours.
Cleber Shimizu


Em qui., 27 de mai. de 2021 às 03:48, Rob Kendal ***@***.***>
escreveu:

**Comment by bpk68** [comment]
Hey Cleber,

Ahh thanks for sharing. I think I've got to the bottom of what's happening for you 😊.

So, there's 3 things to check here:

1. You want to make sure that you've got an .env file in your project root. I created a file called `.env.local` in my project root and placed the single environment variable in it like this... `WP_API_URL=https://clebershimizu.com/graphql/` **Notice the trailing slash on the URL there**
2. Next up, in the `/lib/_api.js` file you'll need to remove anything in the `getAllPosts()` function that isn't relevant in your WP instance. The `getAllPosts()` function is called by the `blog/index.js` file when you visit the `/blog` URL to load a list of the top 20 blog posts. 
At the moment, the vanilla function in the starter repo here is set up to pull in a few extra fields such as 'authorExcerpt' and 'thumbImage'. I added these into my WP instance using Advanced Custom Fields. I suspect you don't have them in yours out of the box so you need to either add them exactly like they're called here or (more likely) just remove them. 

See this screenshot for the idea.

![image](https://user-images.githubusercontent.com/38687284/119939754-39bad300-bf86-11eb-8c91-62e9e71f4b23.png)

3. Finally, in the `pages/blog/index.js` file, you'll need to remove the reference(s) to the fields we just removed in the `_api.js` file or you'll get an error on the front end. Again, here's a screenshot of what I did locally to clean this up:

![image](https://user-images.githubusercontent.com/38687284/119940424-0fb5e080-bf87-11eb-87c2-dcfce9bd34ae.png)

With all of that done, still using your domain you kindly provided, here's the result of me running the project locally:

![image](https://user-images.githubusercontent.com/38687284/119939522-eb0d3900-bf85-11eb-943b-6aed3c80bf77.png)

**Comment by bpk68** [comment]
If you're still getting stuck or need helping adding in some custom fields, etc. then let me know and we can sort something out away from the issues in here and we'll get you up and running in no time 😊
